(() => {
  const baseSets={hero:{idle:['hero_idle1','hero_idle2'],walk:['hero_walk1','hero_walk2'],attack:['hero_attack1'],hurt:['hero_hurt'],dead:['hero_dead']},goblin:{idle:['goblin_idle1','goblin_idle2'],attack:['goblin_attack','goblin_idle1']},wolf:{idle:['wolf_idle1','wolf_idle2']},golem:{idle:['golem_idle1','golem_idle2']},knight:{idle:['knight_idle1','knight_idle2']}};
  const classSets={Warrior:{idle:['warrior_idle','warrior_idle'],walk:['warrior_idle','warrior_idle'],attack:['warrior_attack'],hurt:['warrior_idle'],dead:['warrior_idle']},Ranger:{idle:['ranger_idle','ranger_idle'],walk:['ranger_idle','ranger_idle'],attack:['ranger_attack'],hurt:['ranger_idle'],dead:['ranger_idle']},Mage:{idle:['mage_idle','mage_idle'],walk:['mage_idle','mage_idle'],attack:['mage_cast'],hurt:['mage_idle'],dead:['mage_idle']},Assassin:{idle:['assassin_idle','assassin_idle'],walk:['assassin_idle','assassin_idle'],attack:['assassin_attack'],hurt:['assassin_idle'],dead:['assassin_idle']}};
  let frame=0,mode='idle',timer;
  function setUse(el,id,source){const u=el?.querySelector('use');if(u)u.setAttribute('href',`${source}#${id}`)}
  function tick(){frame++;const cls=localStorage.getItem('mma-rpg-class')||'Warrior',hero=(classSets[cls]||classSets.Warrior)[mode]||classSets[cls].idle;baseSets.hero;document.querySelectorAll('.player-sprite,.sprite-hero').forEach(el=>setUse(el,hero[frame%hero.length],'assets/sprite-sheet-32.svg'));const m=document.querySelector('#monsterImage');if(m){const key=m.querySelector('use')?.getAttribute('href')?.split('#').pop()||'goblin',type=key.includes('wolf')?'wolf':key.includes('golem')?'golem':key.includes('knight')?'knight':'goblin',arr=(baseSets[type][mode]||baseSets[type].idle);setUse(m,arr[frame%arr.length],'assets/animation-sprites.svg')}}
  function animateMode(next,duration=0){mode=next;if(duration){clearTimeout(timer);timer=setTimeout(()=>mode='idle',duration)}}
  window.mmaAnim={mode:animateMode};
  document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){mode='walk';clearTimeout(timer);timer=setTimeout(()=>mode='idle',180)}});
  window.addEventListener('load',()=>{const map=document.querySelector('#worldMap');if(map){map.style.background='url("assets/greenvale-map.svg") center/cover';map.querySelectorAll('.tile').forEach(t=>t.style.backgroundColor='transparent')}setInterval(tick,360)});
  document.addEventListener('click',e=>{if(e.target.closest('#attackBtn,#skillBtn'))animateMode('attack',500);if(e.target.closest('#healBtn,#potionBtn'))animateMode('hurt',500)});
})();