const base={level:10,exp:0,gold:250,hp:240,maxHp:240,mp:80,maxMp:80,str:24,agi:18,int:12,vit:22};
let state={hero:{...base},monster:{name:'Training Goblin',level:8,hp:180,maxHp:180,str:17,def:9},inventory:[{id:'iron_sword',name:'Iron Sword',type:'Weapon',rarity:'Common',atk:18,str:4},{id:'steel_sword',name:'Steel Sword',type:'Weapon',rarity:'Rare',atk:31,str:8},{id:'leather_armor',name:'Leather Armor',type:'Armor',rarity:'Common',def:12,vit:3},{id:'knight_armor',name:'Knight Armor',type:'Armor',rarity:'Rare',def:28,vit:9},{id:'ruby_ring',name:'Ruby Ring',type:'Ring',rarity:'Epic',atk:10,int:8}],equipment:{Weapon:'iron_sword',Armor:'leather_armor',Ring:null},log:['Welcome to MMA : RPG — single-player combat lab.']};
const $=id=>document.getElementById(id); const item=id=>state.inventory.find(x=>x.id===id);
function stats(){let s={...state.hero};Object.values(state.equipment).forEach(id=>{let x=item(id);if(x)for(const k of ['atk','def','str','agi','int','vit'])s[k]=(s[k]||0)+(x[k]||0)});s.attack=Math.floor((s.str*1.8)+(s.agi*.35)+(s.atk||0));s.defense=Math.floor(s.vit*.8+(s.def||0));return s}
function log(t){state.log.unshift(t);state.log=state.log.slice(0,30)}
function render(){let s=stats();$('heroCard').innerHTML=`<div class="card"><b>Lv.${state.hero.level} Adventurer</b><br><span class="muted">ATK ${s.attack} · DEF ${s.defense} · STR ${s.str} · AGI ${s.agi}</span></div>`;$('monsterCard').innerHTML=`<div class="card"><b>${state.monster.name}</b><br><span class="muted">Lv.${state.monster.level} · STR ${state.monster.str} · DEF ${state.monster.def}</span></div>`;$('heroHpBar').style.width=`${state.hero.hp/state.hero.maxHp*100}%`;$('monsterHpBar').style.width=`${Math.max(0,state.monster.hp)/state.monster.maxHp*100}%`;$('combatLog').innerHTML=state.log.map(x=>`<div>${x}</div>`).join('');
$('characterView').innerHTML=`<div class="items"><div class="item"><h3>Adventurer</h3>Level ${state.hero.level}<br>EXP ${state.hero.exp}/100<br>Gold ${state.hero.gold}</div><div class="item"><h3>Resources</h3>HP ${state.hero.hp}/${state.hero.maxHp}<br>MP ${state.hero.mp}/${state.hero.maxMp}</div></div>`;
$('inventoryView').innerHTML=state.inventory.map(x=>`<div class="item"><h3>${x.name}</h3><div class="rarity">${x.rarity} · ${x.type}</div><p>${desc(x)}</p><button onclick="equip('${x.id}')">Equip</button></div>`).join('');
$('equipmentView').innerHTML=Object.entries(state.equipment).map(([slot,id])=>`<div class="equip-slot"><b>${slot}</b><p>${id?item(id).name:'Empty'}</p>${id?`<button onclick="unequip('${slot}')">Unequip</button>`:''}</div>`).join('');
$('statsView').innerHTML=Object.entries(s).filter(([k])=>['str','agi','int','vit','atk','def','attack','defense'].includes(k)).map(([k,v])=>`<div class="stat"><span>${k.toUpperCase()}</span><b>${v}</b></div>`).join('');$('lootView').innerHTML=state.inventory.slice(-6).map(x=>`<div class="item"><h3>${x.name}</h3><span class="rarity">${x.rarity}</span><p>${desc(x)}</p></div>`).join('')}
function desc(x){return Object.entries(x).filter(([k])=>['atk','def','str','agi','int','vit'].includes(k)).map(([k,v])=>`${k.toUpperCase()} +${v}`).join(' · ')||'No bonus'}
function equip(id){let x=item(id);state.equipment[x.type==='Weapon'?'Weapon':x.type==='Armor'?'Armor':'Ring']=id;log(`Equipped ${x.name}.`);render()}
function unequip(slot){state.equipment[slot]=null;log(`Unequipped ${slot}.`);render()}
function attack(){let s=stats(),d=Math.max(1,s.attack-state.monster.def+Math.floor(Math.random()*12)-5);state.monster.hp-=d;log(`You hit ${state.monster.name} for ${d} damage.`);if(state.monster.hp<=0){let gold=25+Math.floor(Math.random()*50);state.hero.gold+=gold;state.hero.exp+=35;log(`Victory! +${gold} gold, +35 EXP.`);drop();newMonster()}else monsterAttack();render()}
function monsterAttack(){let s=stats(),d=Math.max(1,state.monster.str-s.defense+Math.floor(Math.random()*8));state.hero.hp=Math.max(0,state.hero.hp-d);log(`${state.monster.name} hits you for ${d}.`);if(state.hero.hp===0){log('You were defeated. Restored to full HP.');state.hero.hp=state.hero.maxHp}}
function heal(){let n=Math.min(50,state.hero.maxHp-state.hero.hp);state.hero.hp+=n;state.hero.mp=Math.max(0,state.hero.mp-10);log(`Recovered ${n} HP.`);render()}
function newMonster(){let names=['Training Goblin','Forest Wolf','Stone Golem','Dark Knight'];let n=names[Math.floor(Math.random()*names.length)],lv=state.hero.level-1+Math.floor(Math.random()*4);state.monster={name:n,level:lv,hp:120+lv*18,maxHp:120+lv*18,str:12+lv*2,def:6+Math.floor(lv*1.1)}}
function drop(){let r=Math.random();let drops=r>.9?{id:'ruby_ring2',name:'Ruby Ring+',type:'Ring',rarity:'Epic',atk:16,int:10}:r>.65?{id:'steel_sword2',name:'Tempered Steel Sword',type:'Weapon',rarity:'Rare',atk:38,str:10}:{id:'potion',name:'Health Potion',type:'Consumable',rarity:'Common'};if(!state.inventory.some(x=>x.id===drops.id))state.inventory.push(drops);log(`Loot acquired: ${drops.name}.`)}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});$('attackBtn').onclick=attack;$('healBtn').onclick=heal;$('resetBtn').onclick=()=>{location.reload()};render();
